/**:
    ros__parameters:
        common:
            lid_topic: "/unilidar/cloud"
            imu_topic: "/unilidar/imu"
            con_frame: false # true: if you need to combine several LiDAR frames into one
            con_frame_num: 1 # the number of frames combined
            cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
            cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency
            time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
                                        # the timesample of IMU is transferred from the current timeline to LiDAR's timeline by subtracting this value

        preprocess:
            lidar_type: 5
            scan_line: 18
            timestamp_unit: 0           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 0.5

        mapping:
            imu_en: false # disable IMU for LiDAR-only SLAM
            start_in_aggressive_motion: false
            extrinsic_est_en: false
            imu_time_inte: 0.004
            satu_acc: 30.0
            satu_gyro: 35.0
            acc_norm: 9.81
            lidar_meas_cov: 0.1
            acc_cov_output: 100.0
            gyr_cov_output: 100.0
            b_acc_cov: 0.01
            b_gyr_cov: 0.01
            imu_meas_acc_cov: 1.0
            imu_meas_omg_cov: 1.0
            gyr_cov_input: 0.1
            acc_cov_input: 1.0
            plane_thr: 0.05
            match_s: 81.0
            fov_degree: 180.0
            det_range: 50.0
            gravity_align: false # disable gravity alignment for LiDAR-only
            gravity: [0.0, 0.0, -9.810]
            gravity_init: [0.0, 0.0, -9.810]

            # transform from imu to lidar (not used when imu_en is false)
            extrinsic_T: [ 0.0, 0.0, 0.0]
            extrinsic_R: [ 1.0, 0.0, 0.0,
                           0.0, 1.0, 0.0,
                           0.0, 0.0, 1.0 ]

        odometry:
            publish_odometry_without_downsample: true

        publish:
            path_en: true
            scan_publish_en: true
            scan_bodyframe_pub_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1